patients_db: list[dict[str, (int | str | list[str])]] = [
    {
        "ID": 1,
        "Name": "Liam Gallagher",
        "Age": 68,
        "Gender": "Male",
        "Contact Info": "liam.g@email.com, 555-0101",
        "Procedure Undertaken": "Coronary Angioplasty with Stent",
        "Procedure Results": "Successful. Restored blood flow to LAD artery.",
        "Prescriptions": ["Atorvastatin 40mg", "Clopidogrel 75mg"],
    },
    {
        "ID": 2,
        "Name": "Olivia Chen",
        "Age": 75,
        "Gender": "Female",
        "Contact Info": "o.chen@email.com, 555-0102",
        "Procedure Undertaken": "Left Hip Replacement (Arthroplasty)",
        "Procedure Results": "Excellent implant positioning. Patient ambulatory with support.",
        "Prescriptions": ["Oxycodone 5mg (as needed)", "Enoxaparin 40mg (prophylaxis)"],
    },
    {
        "ID": 3,
        "Name": "Noah Patel",
        "Age": 34,
        "Gender": "Male",
        "Contact Info": "noah.p@email.com, 555-0103",
        "Procedure Undertaken": "Appendectomy (Laparoscopic)",
        "Procedure Results": "Uncomplicated removal of inflamed appendix.",
        "Prescriptions": ["Cefoxitin 1g IV (post-op)", "Ibuprofen 600mg"],
    },
    {
        "ID": 4,
        "Name": "Emma Rodriguez",
        "Age": 29,
        "Gender": "Female",
        "Contact Info": "emma.r@email.com, 555-0104",
        "Procedure Undertaken": "Wisdom Tooth Extraction (All four)",
        "Procedure Results": "All four impacted molars removed successfully. Minor swelling.",
        "Prescriptions": ["Amoxicillin 500mg", "Hydrocodone/Acetaminophen 5-325"],
    },
    {
        "ID": 5,
        "Name": "William Kim",
        "Age": 52,
        "Gender": "Male",
        "Contact Info": "will.k@email.com, 555-0105",
        "Procedure Undertaken": "Screening Colonoscopy",
        "Procedure Results": "Two benign polyps identified and removed.",
        "Prescriptions": ["Polyethylene Glycol (prep)", "Famotidine 20mg (for GERD)"],
    },
    {
        "ID": 6,
        "Name": "Ava Singh",
        "Age": 45,
        "Gender": "Female",
        "Contact Info": "ava.s@email.com, 555-0106",
        "Procedure Undertaken": "Cholecystectomy (Gallbladder Removal)",
        "Procedure Results": "Successful laparoscopic removal. Resolved biliary colic.",
        "Prescriptions": ["Ketorolac 10mg", "Ondansetron 4mg (for nausea)"],
    },
    {
        "ID": 7,
        "Name": "James Johnson",
        "Age": 72,
        "Gender": "Male",
        "Contact Info": "j.johnson@email.com, 555-0107",
        "Procedure Undertaken": "Cataract Surgery (Right Eye)",
        "Procedure Results": "Vision improved from 20/80 to 20/25.",
        "Prescriptions": ["Moxifloxacin eye drops", "Prednisolone Acetate drops"],
    },
    {
        "ID": 8,
        "Name": "Sophia Williams",
        "Age": 24,
        "Gender": "Female",
        "Contact Info": "sophia.w@email.com, 555-0108",
        "Procedure Undertaken": "ACL Reconstruction (Left Knee)",
        "Procedure Results": "Stable graft placement. Full extension achieved.",
        "Prescriptions": ["Cephalexin 500mg", "Naproxen 500mg"],
    },
    {
        "ID": 9,
        "Name": "Benjamin Brown",
        "Age": 61,
        "Gender": "Male",
        "Contact Info": "ben.b@email.com, 555-0109",
        "Procedure Undertaken": "Cardiac Stress Test",
        "Procedure Results": "Test negative for ischemia. Good exercise tolerance.",
        "Prescriptions": ["Metoprolol 50mg", "Lisinopril 10mg"],
    },
    {
        "ID": 10,
        "Name": "Isabella Garcia",
        "Age": 38,
        "Gender": "Female",
        "Contact Info": "isabella.g@email.com, 555-0110",
        "Procedure Undertaken": "Thyroid Nodule Biopsy",
        "Procedure Results": "Fine-needle aspiration results were benign (Bethesda II).",
        "Prescriptions": ["Levothyroxine 75mcg", "Acetaminophen 500mg"],
    },
    {
        "ID": 11,
        "Name": "Mason Miller",
        "Age": 22,
        "Gender": "Male",
        "Contact Info": "mason.m@email.com, 555-0111",
        "Procedure Undertaken": "Tonsillectomy",
        "Procedure Results": "Resolved chronic tonsillitis. Patient recovering well.",
        "Prescriptions": ["Penicillin VK 250mg", "Liquid Tylenol with Codeine"],
    },
    {
        "ID": 12,
        "Name": "Mia Davis",
        "Age": 55,
        "Gender": "Female",
        "Contact Info": "mia.d@email.com, 555-0112",
        "Procedure Undertaken": "Upper Endoscopy (EGD)",
        "Procedure Results": "Mild gastritis identified. H. pylori negative.",
        "Prescriptions": ["Omeprazole 40mg", "Sucralfate 1g"],
    },
    {
        "ID": 13,
        "Name": "Ethan Martinez",
        "Age": 41,
        "Gender": "Male",
        "Contact Info": "ethan.m@email.com, 555-0113",
        "Procedure Undertaken": "Vasectomy",
        "Procedure Results": "Successful. Post-procedure semen analysis confirmed azoospermia.",
        "Prescriptions": ["Diazepam 5mg (pre-procedure)", "Ibuprofen 800mg (post-op)"],
    },
    {
        "ID": 14,
        "Name": "Harper Wilson",
        "Age": 31,
        "Gender": "Female",
        "Contact Info": "harper.w@email.com, 555-0114",
        "Procedure Undertaken": "Mole Excision (Back)",
        "Procedure Results": "Shave biopsy showed a benign nevus. Clean margins.",
        "Prescriptions": ["Mupirocin Ointment 2%", "Cetirizine 10mg (for itching)"],
    },
    {
        "ID": 15,
        "Name": "Alexander Anderson",
        "Age": 81,
        "Gender": "Male",
        "Contact Info": "alex.a@email.com, 555-0115",
        "Procedure Undertaken": "Pacemaker Implantation",
        "Procedure Results": "Device functioning correctly. Heart rate stabilized.",
        "Prescriptions": ["Warfarin 5mg", "Diltiazem 120mg"],
    },
    {
        "ID": 16,
        "Name": "Evelyn Taylor",
        "Age": 64,
        "Gender": "Female",
        "Contact Info": "evelyn.t@email.com, 555-0116",
        "Procedure Undertaken": "Carpal Tunnel Release (Right Wrist)",
        "Procedure Results": "Decompression successful. Immediate relief of nocturnal symptoms.",
        "Prescriptions": ["Gabapentin 300mg", "Meloxicam 15mg"],
    },
    {
        "ID": 17,
        "Name": "Daniel Thomas",
        "Age": 28,
        "Gender": "Male",
        "Contact Info": "dan.t@email.com, 555-0117",
        "Procedure Undertaken": "Septoplasty",
        "Procedure Results": "Corrected deviated septum. Improved nasal airflow.",
        "Prescriptions": ["Saline Nasal Spray", "Fluticasone Nasal Spray"],
    },
    {
        "ID": 18,
        "Name": "Charlotte Moore",
        "Age": 49,
        "Gender": "Female",
        "Contact Info": "charlotte.m@email.com, 555-0118",
        "Procedure Undertaken": "Hysterectomy (Laparoscopic)",
        "Procedure Results": "Uterus removed due to fibroids. Patient stable.",
        "Prescriptions": ["Morphine PCA (post-op)", "Docusate Sodium 100mg"],
    },
    {
        "ID": 19,
        "Name": "Michael White",
        "Age": 58,
        "Gender": "Male",
        "Contact Info": "mike.w@email.com, 555-0119",
        "Procedure Undertaken": "Hernia Repair (Inguinal)",
        "Procedure Results": "Mesh repair successful, no tension.",
        "Prescriptions": ["Tramadol 50mg", "Senna 8.6mg"],
    },
    {
        "ID": 20,
        "Name": "Amelia Jackson",
        "Age": 7,
        "Gender": "Female",
        "Contact Info": "jackson.fam@email.com, 555-0120",
        "Procedure Undertaken": "Myringotomy with Tube Insertion",
        "Procedure Results": "Tubes placed bilaterally to resolve chronic ear infections.",
        "Prescriptions": ["Ciprofloxacin/Dexamethasone drops", "Children's Motrin"],
    },
    {
        "ID": 21,
        "Name": "Lucas Harris",
        "Age": 66,
        "Gender": "Male",
        "Contact Info": "lucas.h@email.com, 555-0121",
        "Procedure Undertaken": "TURP (Prostate Resection)",
        "Procedure Results": "Improved urinary flow, decreased post-void residual.",
        "Prescriptions": ["Tamsulosin 0.4mg", "Finasteride 5mg"],
    },
    {
        "ID": 22,
        "Name": "Chloe Martin",
        "Age": 43,
        "Gender": "Female",
        "Contact Info": "chloe.m@email.com, 555-0122",
        "Procedure Undertaken": "Bunionectomy (Left Foot)",
        "Procedure Results": "Deformity corrected. Hardware in good position.",
        "Prescriptions": ["Celecoxib 200mg", "Fentanyl Patch 25mcg"],
    },
    {
        "ID": 23,
        "Name": "Henry Thompson",
        "Age": 50,
        "Gender": "Male",
        "Contact Info": "h.thompson@email.com, 555-0123",
        "Procedure Undertaken": "LASIK Eye Surgery",
        "Procedure Results": "Vision corrected to 20/20 in both eyes.",
        "Prescriptions": ["Loteprednol eye drops", "Gatifloxacin eye drops"],
    },
    {
        "ID": 24,
        "Name": "Zoe Clark",
        "Age": 36,
        "Gender": "Female",
        "Contact Info": "zoe.c@email.com, 555-0124",
        "Procedure Undertaken": "Dilation and Curettage (D&C)",
        "Procedure Results": "Procedure completed to manage abnormal uterine bleeding.",
        "Prescriptions": ["Misoprostol (pre-procedure)", "Doxycycline 100mg"],
    },
    {
        "ID": 25,
        "Name": "Logan Lewis",
        "Age": 19,
        "Gender": "Male",
        "Contact Info": "logan.l@email.com, 555-0125",
        "Procedure Undertaken": "Arthroscopy (Shoulder)",
        "Procedure Results": "Repaired minor labral tear. Debridement performed.",
        "Prescriptions": [
            "Hydroxyzine 25mg (for itching)",
            "Oxycodone/Acetaminophen 5-325",
        ],
    },
]
